// Code generated by MockGen. DO NOT EDIT.
// Source: inference.go
//
// Generated by this command:
//
//	mockgen -source=inference.go -destination=../../mocks/mockllms/inference_mock.gen.go -package mockllms
//

// Package mockllms is a generated GoMock package.
package mockllms

import (
	context "context"
	reflect "reflect"

	llms "github.com/effective-security/gogentic/pkg/llms"
	gomock "go.uber.org/mock/gomock"
)

// MockInferenceModel is a mock of InferenceModel interface.
type MockInferenceModel struct {
	ctrl     *gomock.Controller
	recorder *MockInferenceModelMockRecorder
	isgomock struct{}
}

// MockInferenceModelMockRecorder is the mock recorder for MockInferenceModel.
type MockInferenceModelMockRecorder struct {
	mock *MockInferenceModel
}

// NewMockInferenceModel creates a new mock instance.
func NewMockInferenceModel(ctrl *gomock.Controller) *MockInferenceModel {
	mock := &MockInferenceModel{ctrl: ctrl}
	mock.recorder = &MockInferenceModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInferenceModel) EXPECT() *MockInferenceModelMockRecorder {
	return m.recorder
}

// Infer mocks base method.
func (m *MockInferenceModel) Infer(arg0 context.Context, arg1 llms.InferenceRequest) (*llms.InferenceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Infer", arg0, arg1)
	ret0, _ := ret[0].(*llms.InferenceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Infer indicates an expected call of Infer.
func (mr *MockInferenceModelMockRecorder) Infer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infer", reflect.TypeOf((*MockInferenceModel)(nil).Infer), arg0, arg1)
}

// ValidateInference mocks base method.
func (m *MockInferenceModel) ValidateInference(arg0 llms.InferenceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateInference", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateInference indicates an expected call of ValidateInference.
func (mr *MockInferenceModelMockRecorder) ValidateInference(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateInference", reflect.TypeOf((*MockInferenceModel)(nil).ValidateInference), arg0)
}
