// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/effective-security/gogentic/pkg/llms (interfaces: Model,Batcher)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mockllms/llm_mock.gen.go -package mockllms github.com/effective-security/gogentic/pkg/llms Model,Batcher
//

// Package mockllms is a generated GoMock package.
package mockllms

import (
	context "context"
	reflect "reflect"

	llms "github.com/effective-security/gogentic/pkg/llms"
	gomock "go.uber.org/mock/gomock"
)

// MockModel is a mock of Model interface.
type MockModel struct {
	ctrl     *gomock.Controller
	recorder *MockModelMockRecorder
	isgomock struct{}
}

// MockModelMockRecorder is the mock recorder for MockModel.
type MockModelMockRecorder struct {
	mock *MockModel
}

// NewMockModel creates a new mock instance.
func NewMockModel(ctrl *gomock.Controller) *MockModel {
	mock := &MockModel{ctrl: ctrl}
	mock.recorder = &MockModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModel) EXPECT() *MockModelMockRecorder {
	return m.recorder
}

// GenerateContent mocks base method.
func (m *MockModel) GenerateContent(ctx context.Context, messages []llms.Message, options ...llms.CallOption) (*llms.ContentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, messages}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateContent", varargs...)
	ret0, _ := ret[0].(*llms.ContentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateContent indicates an expected call of GenerateContent.
func (mr *MockModelMockRecorder) GenerateContent(ctx, messages any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, messages}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateContent", reflect.TypeOf((*MockModel)(nil).GenerateContent), varargs...)
}

// GetName mocks base method.
func (m *MockModel) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockModelMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockModel)(nil).GetName))
}

// GetProviderType mocks base method.
func (m *MockModel) GetProviderType() llms.ProviderType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderType")
	ret0, _ := ret[0].(llms.ProviderType)
	return ret0
}

// GetProviderType indicates an expected call of GetProviderType.
func (mr *MockModelMockRecorder) GetProviderType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderType", reflect.TypeOf((*MockModel)(nil).GetProviderType))
}

// MockBatcher is a mock of Batcher interface.
type MockBatcher struct {
	ctrl     *gomock.Controller
	recorder *MockBatcherMockRecorder
	isgomock struct{}
}

// MockBatcherMockRecorder is the mock recorder for MockBatcher.
type MockBatcherMockRecorder struct {
	mock *MockBatcher
}

// NewMockBatcher creates a new mock instance.
func NewMockBatcher(ctrl *gomock.Controller) *MockBatcher {
	mock := &MockBatcher{ctrl: ctrl}
	mock.recorder = &MockBatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatcher) EXPECT() *MockBatcherMockRecorder {
	return m.recorder
}

// CancelBatch mocks base method.
func (m *MockBatcher) CancelBatch(ctx context.Context, batchID string) (*llms.BatchHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBatch", ctx, batchID)
	ret0, _ := ret[0].(*llms.BatchHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelBatch indicates an expected call of CancelBatch.
func (mr *MockBatcherMockRecorder) CancelBatch(ctx, batchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBatch", reflect.TypeOf((*MockBatcher)(nil).CancelBatch), ctx, batchID)
}

// FetchBatchResults mocks base method.
func (m *MockBatcher) FetchBatchResults(ctx context.Context, batchID string) ([]llms.BatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchBatchResults", ctx, batchID)
	ret0, _ := ret[0].([]llms.BatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchBatchResults indicates an expected call of FetchBatchResults.
func (mr *MockBatcherMockRecorder) FetchBatchResults(ctx, batchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchBatchResults", reflect.TypeOf((*MockBatcher)(nil).FetchBatchResults), ctx, batchID)
}

// GetBatch mocks base method.
func (m *MockBatcher) GetBatch(ctx context.Context, batchID string) (*llms.BatchHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBatch", ctx, batchID)
	ret0, _ := ret[0].(*llms.BatchHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBatch indicates an expected call of GetBatch.
func (mr *MockBatcherMockRecorder) GetBatch(ctx, batchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBatch", reflect.TypeOf((*MockBatcher)(nil).GetBatch), ctx, batchID)
}

// SubmitBatch mocks base method.
func (m *MockBatcher) SubmitBatch(ctx context.Context, requests []llms.BatchRequest, options ...llms.BatchSubmitOption) (*llms.BatchHandle, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, requests}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubmitBatch", varargs...)
	ret0, _ := ret[0].(*llms.BatchHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitBatch indicates an expected call of SubmitBatch.
func (mr *MockBatcherMockRecorder) SubmitBatch(ctx, requests any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, requests}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitBatch", reflect.TypeOf((*MockBatcher)(nil).SubmitBatch), varargs...)
}
