// Code generated by MockGen. DO NOT EDIT.
// Source: router.go
//
// Generated by this command:
//
//	mockgen -source=router.go -destination=../mocks/mockrouter/router_mock.gen.go -package mockrouter
//

// Package mockrouter is a generated GoMock package.
package mockrouter

import (
	context "context"
	reflect "reflect"

	router "github.com/effective-security/gogentic/router"
	gomock "go.uber.org/mock/gomock"
)

// MockSelector is a mock of Selector interface.
type MockSelector struct {
	ctrl     *gomock.Controller
	recorder *MockSelectorMockRecorder
	isgomock struct{}
}

// MockSelectorMockRecorder is the mock recorder for MockSelector.
type MockSelectorMockRecorder struct {
	mock *MockSelector
}

// NewMockSelector creates a new mock instance.
func NewMockSelector(ctrl *gomock.Controller) *MockSelector {
	mock := &MockSelector{ctrl: ctrl}
	mock.recorder = &MockSelectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSelector) EXPECT() *MockSelectorMockRecorder {
	return m.recorder
}

// Select mocks base method.
func (m *MockSelector) Select(arg0 context.Context, arg1 router.SelectionInput) (router.Decision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", arg0, arg1)
	ret0, _ := ret[0].(router.Decision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockSelectorMockRecorder) Select(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockSelector)(nil).Select), arg0, arg1)
}

// MockAdmission is a mock of Admission interface.
type MockAdmission struct {
	ctrl     *gomock.Controller
	recorder *MockAdmissionMockRecorder
	isgomock struct{}
}

// MockAdmissionMockRecorder is the mock recorder for MockAdmission.
type MockAdmissionMockRecorder struct {
	mock *MockAdmission
}

// NewMockAdmission creates a new mock instance.
func NewMockAdmission(ctrl *gomock.Controller) *MockAdmission {
	mock := &MockAdmission{ctrl: ctrl}
	mock.recorder = &MockAdmissionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmission) EXPECT() *MockAdmissionMockRecorder {
	return m.recorder
}

// Admit mocks base method.
func (m *MockAdmission) Admit(arg0 context.Context, arg1 router.AdmissionRequest) (func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Admit", arg0, arg1)
	ret0, _ := ret[0].(func())
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Admit indicates an expected call of Admit.
func (mr *MockAdmissionMockRecorder) Admit(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Admit", reflect.TypeOf((*MockAdmission)(nil).Admit), arg0, arg1)
}
