// Code generated by MockGen. DO NOT EDIT.
// Source: exact.go
//
// Generated by this command:
//
//	mockgen -source=exact.go -destination=../../mocks/mockllmfactory/exact_mock.gen.go -package mockllmfactory
//

// Package mockllmfactory is a generated GoMock package.
package mockllmfactory

import (
	context "context"
	reflect "reflect"

	llms "github.com/effective-security/gogentic/pkg/llms"
	gomock "go.uber.org/mock/gomock"
)

// MockExactResolver is a mock of ExactResolver interface.
type MockExactResolver struct {
	ctrl     *gomock.Controller
	recorder *MockExactResolverMockRecorder
	isgomock struct{}
}

// MockExactResolverMockRecorder is the mock recorder for MockExactResolver.
type MockExactResolverMockRecorder struct {
	mock *MockExactResolver
}

// NewMockExactResolver creates a new mock instance.
func NewMockExactResolver(ctrl *gomock.Controller) *MockExactResolver {
	mock := &MockExactResolver{ctrl: ctrl}
	mock.recorder = &MockExactResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExactResolver) EXPECT() *MockExactResolverMockRecorder {
	return m.recorder
}

// GetModelExact mocks base method.
func (m *MockExactResolver) GetModelExact(ctx context.Context, provider, model, orgID string) (llms.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelExact", ctx, provider, model, orgID)
	ret0, _ := ret[0].(llms.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelExact indicates an expected call of GetModelExact.
func (mr *MockExactResolverMockRecorder) GetModelExact(ctx, provider, model, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelExact", reflect.TypeOf((*MockExactResolver)(nil).GetModelExact), ctx, provider, model, orgID)
}
