// Code generated by MockGen. DO NOT EDIT.
// Source: factory.go
//
// Generated by this command:
//
//	mockgen -source=factory.go -destination=../../mocks/mockllmfactory/llmfactory_mock.gen.go -package mockllmfactory
//

// Package mockllmfactory is a generated GoMock package.
package mockllmfactory

import (
	reflect "reflect"

	llmfactory "github.com/effective-security/gogentic/pkg/llmfactory"
	llms "github.com/effective-security/gogentic/pkg/llms"
	skills "github.com/effective-security/gogentic/skills"
	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// GetModel mocks base method.
func (m *MockFactory) GetModel(opts llmfactory.ModelOptions) (llms.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModel", opts)
	ret0, _ := ret[0].(llms.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModel indicates an expected call of GetModel.
func (mr *MockFactoryMockRecorder) GetModel(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModel", reflect.TypeOf((*MockFactory)(nil).GetModel), opts)
}

// Skills mocks base method.
func (m *MockFactory) Skills(agent string, tags ...string) skills.Skills {
	m.ctrl.T.Helper()
	varargs := []any{agent}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Skills", varargs...)
	ret0, _ := ret[0].(skills.Skills)
	return ret0
}

// Skills indicates an expected call of Skills.
func (mr *MockFactoryMockRecorder) Skills(agent any, tags ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{agent}, tags...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Skills", reflect.TypeOf((*MockFactory)(nil).Skills), varargs...)
}
